### PR TITLE
[Private] Hyperlink fixes

### PR DESCRIPTION
**Pull request by mvandertuin**
I found some broken links at the index.md page (which is automatically transformed into http://docs.opentripplanner.org/) and fixed them.

Could you please check whether I corrected them correctly? 
Please note that this PR should NOT be merged, as can be read here: https://github.com/delftswa2016/course-info-2016/blob/master/faq.md#git--github at list item 10. 
If the discussion is done, we should close this PR, and open a new one.

### CODE REVIEW

**Comment by mvandertuin** [comment]
Proposed text for the issue to be created before submitting the PR at OpenTripPlanner. Not sure whether it's a good idea yet to mention the course already. What is your opinion about this?

## 

While discovering OTP as a part of the Delft Students On Software Architecture 2016 project (see also http://delftswa.github.io/), I noticed a few broken links at the index page of the documentation:
- The links to the Conveyal blog do not work due to a slash at the end of the links
- The translation page is not present at the documentation but can be found as a ReadMe on GitHub itself.
- The link to the History page should be History instead of Project-History

I will add a pull request fixing the links.

**Comment by thomhubers** [comment]
However I think those URL's should just work they apparently don't, which is a weird thing. This PR thus seems an improvement to me. It's also helpful to gain some trust of the project's main stakeholders by contributing a little. Nice start!

**Comment by acroockewit** [comment]
Hyperlinks are working.
Why would we not mention the Software Architecture project already? To first gain some trust?

**Comment by acroockewit** [comment]
(Except the history link..)

**Comment by pstekieli** [comment]
:ballot_box_with_check: :+1:

**Comment by mvandertuin** [comment]
Thanks :smile: I'll close this  PR and create a new one so our discussion won't be visible for the OTP community.

**Pull request closed without merging**
